#内配置文件
import os
#set OPPS_CONFIG=XXX
SERVER_POET = 2000
DEBUG = False
SQLALCHEMY_ECHO = False
SQLALCHEMY_DATABASE_URI = 'mysql://imooc:666666@47.121.116.233/food_db?charset=utf8'
SQLALCHEMY_TRACK_MODIFICATIONS = False


